### ISSUE TITLE
Move to using flysystem to make it easier to add other storage backends?

### ISSUE THREAD

**Issue by oparoz** [kanboard/plugin-s3#1]
Since there are a lot of possible storage mechanisms, maybe it would be good to use an abstraction layer which makes it easier to write Kanboard storage plugins?

http://flysystem.thephpleague.com/api/

[![Bountysource](https://www.bountysource.com/badge/issue?issue_id=27344191)](https://www.bountysource.com/issues/27344191-move-to-using-flysystem-to-make-it-easier-to-add-other-storage-backends?utm_source=27344191&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by fguillot** [comment]
The storage plugin system doesn't abstract the filesystem but object storages.
